---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tus-php-redis-pv
  labels:
    namespace: local
spec:
  storageClassName: redis
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/tus-php/redis
