---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tus-php-uploads-pv
  labels:
    namespace: local
spec:
  storageClassName: uploads
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/tus-php/uploads
