---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tus-php-redis-pv-claim
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
