---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tus-php-uploads-pv-claim
spec:
  storageClassName: uploads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
